### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <:> at index 2

### ISSUE THREAD

**Issue by ZeeWanderer** [sengi12/ghidra-hexEditor#2]
```
Error running script: HexEditor.java
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /F:/Program Files (x86)/Steam/steamapps/common/Horizon Zero Dawn/HorizonZeroDawn.exe
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /F:/Program Files (x86)/Steam/steamapps/common/Horizon Zero Dawn/HorizonZeroDawn.exe
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at resources.binEdit.<init>(binEdit.java:149)
	at resources.MainWindow.<init>(MainWindow.java:138)
	at HexEditor.run(HexEditor.java:45)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: E:\Tools\jdk-11.0.8.10-hotspot
JVM Version: AdoptOpenJDK 11.0.8
OS: Windows 10 10.0 amd64
```

EDIT: Error persists after update. I updated repo and did a cleanup.

**Comment by sengi12** [comment]
Thanks @ZeeWanderer for bringing this to my attention. It's simply because of the spaces in the file path. I'll be sure to post a fix and an update soon to address this issue.

**Comment by sengi12** [comment]
@ZeeWanderer just posted a new update to potentially fix the issue. Let me know if you run into any issues. P.S. be sure to run the ./cleanup script before trying out the new update otherwise it won't recompile in Ghidra

**Comment by ZeeWanderer** [comment]
The error persists after the update. I updated repo and did a cleanup

**Comment by sengi12** [comment]
@ZeeWanderer I apologize for just getting back to this. (Been a busy few months with school/work. I just found out the problem though. For some reason when the Ghidra API runs `String path = currentProgram.getExecutablePath();` within Windows 10, it places an extra `/` at the beginning of the path.

I added a fix that basically checks for the OS and removes that character if it exists. I got it to work on my Windows 10 VM. Please try and let me know if it works on your end. Like mentioned previously, be sure to run `python ./cleanup` script before trying out the new update otherwise it won't recompile in Ghidra.

**Comment by sengi12** [comment]
Since I got this to work on my Windows 10 environment, I'm going to close this issue. If you continue to have issues, feel free to comment and I'll jump right onto it, but i believe the ` java.nio.file.InvalidPathException: Illegal char <:> at index 2 #2 ` issue is fixed.

**Comment by fluxany** [comment]
Copy the lines referencing Windows 10 and change the number 10 to 11. This fixes the issue.
